name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.x'
    - name: install altcover
      run: dotnet tool install --global altcover.visualizer --version  8.6.14
    - name: Install dependencies
      run: cd aliyun-net-credentials-unit-tests/ && dotnet add package AltCover && cd ../ && dotnet restore && dotnet build
    - name: Setup OIDC
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          const coreDemo = require('@actions/core');
          const idToken = await coreDemo.getIDToken('sts.aliyuncs.com');
          const fsx = require('fs/promises');
          await fsx.writeFile('/tmp/oidc_token', idToken);
    - name: Integration Test
      run: dotnet test aliyun-net-credentials-integration-tests/
      env:
        ALIBABA_CLOUD_OIDC_PROVIDER_ARN: ${{ secrets.ALIBABA_CLOUD_OIDC_PROVIDER_ARN }}
        ALIBABA_CLOUD_OIDC_TOKEN_FILE: "/tmp/oidc_token"
        ALIBABA_CLOUD_ROLE_ARN: ${{ secrets.ALIBABA_CLOUD_ROLE_ARN }}
    - name: Test
      run: dotnet test aliyun-net-credentials-unit-tests/ /p:AltCover=true --framework netcoreapp3.1
    - name: Upload code coverage report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        framework: [net45, netcoreapp3.1]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.x'

      - name: Restore dependencies
        run: dotnet restore aliyun-net-credentials-unit-tests/aliyun-net-credentials-unit-tests.csproj
        
      - name: Ensure Tests Compile
        run: dotnet build aliyun-net-credentials-unit-tests/aliyun-net-credentials-unit-tests.csproj --configuration Debug --framework ${{ matrix.framework }}

      - name: Run Unit Tests
        run: dotnet test aliyun-net-credentials-unit-tests/aliyun-net-credentials-unit-tests.csproj --no-build --logger "trx;LogFileName=TestResults_${{ matrix.framework }}.trx" --framework ${{ matrix.framework }}